spring:
  datasource:
    url: jdbc:mysql://fnjv44kcr8ym4e3e:nm7i2x00jsuv7obm@e7qyahb3d90mletd.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/v6eqjfqi1n8d9orn
    username: fnjv44kcr8ym4e3e
    password: nm7i2x00jsuv7obm
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5       # Nombre max de connexions simultanées
      minimum-idle: 2            # Nombre min de connexions inactives
      idle-timeout: 10000        # Ferme une connexion inactive après 10s
      max-lifetime: 20000        # Durée max d’une connexion avant fermeture (20s)
      connection-timeout: 10000  # Timeout max pour obtenir une connexion (10s)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mehdi.favreau@gmail.com
    password: zdui itfh xvfj qhis
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

logging:
  level:
    root: INFO
    fr.ecoride.backend: DEBUG
  file:
    name: logs/app.log