spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5       # Nombre max de connexions simultanées
      minimum-idle: 2            # Nombre min de connexions inactives
      idle-timeout: 10000        # Ferme une connexion inactive après 10s
      max-lifetime: 60000        # Durée max d’une connexion avant fermeture (60s)
      connection-timeout: 30000  # Timeout max pour obtenir une connexion (30s)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mehdi.favreau@gmail.com
    password: zdui itfh xvfj qhis
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

logging:
  level:
    root: INFO
    fr.ecoride.backend: DEBUG
  file:
    name: logs/app.log
